/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    portfolio: Portfolio;
    testimonials: Testimonial;
    posts: Post;
    'questionnaire-templates': QuestionnaireTemplate;
    'questionnaire-invites': QuestionnaireInvite;
    'questionnaire-responses': QuestionnaireResponse;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'questionnaire-templates': QuestionnaireTemplatesSelect<false> | QuestionnaireTemplatesSelect<true>;
    'questionnaire-invites': QuestionnaireInvitesSelect<false> | QuestionnaireInvitesSelect<true>;
    'questionnaire-responses': QuestionnaireResponsesSelect<false> | QuestionnaireResponsesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt' | 'en' | 'fr') | ('pt' | 'en' | 'fr')[];
  globals: {};
  globalsSelect: {};
  locale: 'pt' | 'en' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Biblioteca central de imagens e ficheiros. Tudo o que carrega aqui fica disponível para usar em Portefólio (capa), Blog (capa), Testemunhos (avatar). Pode também carregar directamente a partir desses formulários — fica aqui automaticamente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * As três linhas de oferta — Desenvolvimento, Infra & Cloud, Comércio. O slug controla a URL pública (/servicos/<slug>).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL slug (ex. desenvolvimento, infra-cloud, comercio).
   */
  slug: string;
  /**
   * Ordem de apresentação (menor = primeiro).
   */
  order?: number | null;
  /**
   * Caminho do ícone SVG (ex. /servicos/Desenvolvimento de Software.svg).
   */
  icon: string;
  /**
   * Resumo curto usado nos cartões da homepage e listagem.
   */
  shortDescription: string;
  /**
   * Texto longo da página de detalhe do serviço.
   */
  description: string;
  /**
   * Preço inicial em Kz (0 = 'Sob consulta').
   */
  startingPrice?: number | null;
  deliverables?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  pricing?:
    | {
        name: string;
        description?: string | null;
        features?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        priceMin?: number | null;
        priceMax?: number | null;
        /**
         * Destaque visual (badge 'recomendado').
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  priceTable?:
    | {
        item: string;
        min?: number | null;
        max?: number | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  description: string;
  category: 'website' | 'app-mobile' | 'app-desktop' | 'sistema' | 'infra-cloud';
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Imagem que aparece no cartão do projecto. Carregue um ficheiro novo ou escolha um existente da Media library.
   */
  image?: (number | null) | Media;
  /**
   * Link público do projecto (opcional).
   */
  url?: string | null;
  /**
   * Se marcado, o nome do cliente fica oculto no site.
   */
  confidential?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role: string;
  company: string;
  content: string;
  /**
   * Foto da pessoa (opcional). Se não houver, mostra-se um círculo com a inicial.
   */
  avatar?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  /**
   * Conteúdo do artigo em Markdown (renderizado com MDX).
   */
  content: string;
  /**
   * Imagem destacada do artigo (cartão na listagem do blog e topo do post). Carregue um ficheiro novo ou escolha um existente da Media library.
   */
  coverImage?: (number | null) | Media;
  /**
   * Apenas usado se 'Imagem de capa' não estiver definido. Caminho relativo a /public (ex. /placeholder-blog-1.svg).
   */
  imagePath?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  author?: string | null;
  /**
   * Tempo de leitura estimado (ex. '5 min').
   */
  readTime?: string | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Modelos reutilizáveis. Para cada cliente cria-se um Convite que gera link público.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire-templates".
 */
export interface QuestionnaireTemplate {
  id: number;
  title: string;
  /**
   * Identificador interno (não público).
   */
  slug: string;
  /**
   * Apenas modelos activos podem gerar Convites.
   */
  active?: boolean | null;
  /**
   * Mensagem mostrada ao cliente no topo do formulário.
   */
  introMessage?: string | null;
  /**
   * Mensagem mostrada ao cliente após submissão.
   */
  thankYouMessage?: string | null;
  questions?:
    | {
        /**
         * Identificador único da pergunta (ex. 'budget', 'timeline'). Sem espaços.
         */
        key: string;
        label: string;
        helpText?: string | null;
        type:
          | 'shortText'
          | 'longText'
          | 'email'
          | 'phone'
          | 'number'
          | 'date'
          | 'yesNo'
          | 'singleChoice'
          | 'multipleChoice'
          | 'scale';
        required?: boolean | null;
        /**
         * Apenas para Escolha Única / Escolha Múltipla. Ignorar para outros tipos.
         */
        options?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cada Convite gera um link único anónimo a enviar ao cliente. O link expira na data definida ou após submissão.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire-invites".
 */
export interface QuestionnaireInvite {
  id: number;
  template: number | QuestionnaireTemplate;
  /**
   * Idioma em que o questionário será apresentado ao cliente.
   */
  locale: 'pt' | 'en' | 'fr';
  /**
   * Nome do cliente (referência interna; não exposto).
   */
  clientName?: string | null;
  /**
   * Email para enviar o link (referência interna).
   */
  clientEmail?: string | null;
  /**
   * Empresa do cliente (referência interna).
   */
  clientCompany?: string | null;
  /**
   * Notas internas (não visíveis ao cliente).
   */
  notes?: string | null;
  /**
   * Opcional. Após esta data o link deixa de funcionar.
   */
  expiresAt?: string | null;
  /**
   * Gerado automaticamente. Não editar.
   */
  token?: string | null;
  status?: ('pending' | 'submitted' | 'expired') | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissões dos clientes via link público.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire-responses".
 */
export interface QuestionnaireResponse {
  id: number;
  invite: number | QuestionnaireInvite;
  template: number | QuestionnaireTemplate;
  clientName?: string | null;
  clientEmail?: string | null;
  clientPhone?: string | null;
  answers?:
    | {
        questionKey?: string | null;
        questionLabel?: string | null;
        questionType?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'questionnaire-templates';
        value: number | QuestionnaireTemplate;
      } | null)
    | ({
        relationTo: 'questionnaire-invites';
        value: number | QuestionnaireInvite;
      } | null)
    | ({
        relationTo: 'questionnaire-responses';
        value: number | QuestionnaireResponse;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  icon?: T;
  shortDescription?: T;
  description?: T;
  startingPrice?: T;
  deliverables?:
    | T
    | {
        value?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        value?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        name?: T;
        description?: T;
        features?:
          | T
          | {
              value?: T;
              id?: T;
            };
        priceMin?: T;
        priceMax?: T;
        highlight?: T;
        id?: T;
      };
  priceTable?:
    | T
    | {
        item?: T;
        min?: T;
        max?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  image?: T;
  url?: T;
  confidential?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  content?: T;
  avatar?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  imagePath?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  author?: T;
  readTime?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire-templates_select".
 */
export interface QuestionnaireTemplatesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  active?: T;
  introMessage?: T;
  thankYouMessage?: T;
  questions?:
    | T
    | {
        key?: T;
        label?: T;
        helpText?: T;
        type?: T;
        required?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire-invites_select".
 */
export interface QuestionnaireInvitesSelect<T extends boolean = true> {
  template?: T;
  locale?: T;
  clientName?: T;
  clientEmail?: T;
  clientCompany?: T;
  notes?: T;
  expiresAt?: T;
  token?: T;
  status?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questionnaire-responses_select".
 */
export interface QuestionnaireResponsesSelect<T extends boolean = true> {
  invite?: T;
  template?: T;
  clientName?: T;
  clientEmail?: T;
  clientPhone?: T;
  answers?:
    | T
    | {
        questionKey?: T;
        questionLabel?: T;
        questionType?: T;
        value?: T;
        id?: T;
      };
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}